#!/bin/bash
set -euo pipefail

local:make() {
    pushd $2 \
        && makepkg \
            --clean \
            --cleanbuild \
            --rmdeps \
            --syncdeps \
            --force \
            --noconfirm \
    && popd
}

aur:make() {
    local:make $2
    pushd $2 && makepkg --printsrcinfo > .SRCINFO && popd
}

aur:push() {
    git subtree push --prefix $2 git+ssh://aur@aur.archlinux.org/$2 master
}

aur:fix-refusing-to-merge-unrelated-histories() {
    git subtree pull --prefix $2 --squash git+ssh://aur@aur.archlinux.org/$2 master
}

help() {
    cat "$0" | grep "^.*() {$" | cut -d "(" -f1
}

if [ ! -z ${1:-} ]; then
    "$1" "$@"
else
    help
fi
